name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us investigate.

  - type: dropdown
    id: running-mode
    attributes:
      label: Running Mode
      description: How were you running Claudia when the bug occurred?
      options:
        - Keyboard + Simulation
        - Keyboard + Hardware
        - Voice + Simulation
        - Voice + Hardware
        - Other (describe below)
    validations:
      required: true

  - type: dropdown
    id: router-mode
    attributes:
      label: Router Mode
      description: Which LLM routing mode was active?
      options:
        - dual (default)
        - legacy
        - shadow
        - Unknown / Not sure
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start Claudia with `python3 production_commander.py`
        2. Enter command '...'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: |
        Relevant log output. Check `logs/` directory for audit logs.
        Paste error messages, tracebacks, or audit log entries.
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details.
      placeholder: |
        - OS: Ubuntu 20.04 (aarch64) / macOS / etc.
        - Python: 3.8.10
        - Ollama version: x.x.x
        - LLM model: claudia-7b:v2.0
        - Robot: Go2 (if hardware mode)
        - Jetson: Orin NX (if applicable)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here.
        Screenshots, config files, or related issues.
    validations:
      required: false
