name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the information below.

        **Note:** Features that affect robot action execution or safety systems
        require additional safety review.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: |
        What problem does this feature solve?
        A clear description of the pain point or use case.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear description of what you'd like to happen.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system does this feature affect?
      multiple: true
      options:
        - Brain / LLM Pipeline
        - Action Registry
        - SafetyCompiler
        - Voice / ASR Pipeline
        - Robot Controller
        - LED System
        - CLI / Commander
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: safety-impact
    attributes:
      label: Safety Impact
      description: Does this feature affect robot safety systems?
      options:
        - "No — Does not affect safety systems"
        - "Low — Minor changes, no safety bypass"
        - "Medium — Modifies action behavior or adds new actions"
        - "High — Affects SafetyCompiler, battery gating, or emergency stop"
    validations:
      required: true

  - type: dropdown
    id: hardware-required
    attributes:
      label: Hardware Requirement
      description: Does this feature require hardware for development or testing?
      options:
        - "No — Can be developed and tested in simulation"
        - "Testing only — Development in simulation, hardware testing needed"
        - "Yes — Requires physical robot for development"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context, mockups, or references.
        Links to related projects, papers, or documentation.
    validations:
      required: false
